-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 19:13:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bag_of_tricks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bag_of_tricks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bag_of_tricks` DEFAULT CHARACTER SET utf8 ;
USE `bag_of_tricks` ;

-- -----------------------------------------------------
-- Table `bag_of_tricks`.`bag_node_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`bag_node_category` (
  `bag_node_category_id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`bag_node_category_id`));


-- -----------------------------------------------------
-- Table `bag_of_tricks`.`trick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`trick` (
  `trick_id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`trick_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bag_of_tricks`.`bag_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`bag_node` (
  `bag_node_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `bag_node_category_id` INT NULL,
  `bag_node_type_cd` VARCHAR(10) NOT NULL,
  `trick_id` INT NULL,
  PRIMARY KEY (`bag_node_id`),
  INDEX `fk_bag_bag_category1_idx` (`bag_node_category_id` ASC),
  INDEX `fk_bag_node_trick1_idx` (`trick_id` ASC),
  CONSTRAINT `fk_bag_bag_category1`
    FOREIGN KEY (`bag_node_category_id`)
    REFERENCES `bag_of_tricks`.`bag_node_category` (`bag_node_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bag_node_trick1`
    FOREIGN KEY (`trick_id`)
    REFERENCES `bag_of_tricks`.`trick` (`trick_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bag_of_tricks`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password_salt` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(50) NULL,
  `github_username` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `bag_of_tricks`.`bag_node_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`bag_node_reference` (
  `bag_node_parent_id` INT NOT NULL,
  `bag_node_child_id` INT NOT NULL,
  INDEX `fk_bag_node_reference_bag_node2_idx` (`bag_node_child_id` ASC),
  PRIMARY KEY (`bag_node_parent_id`, `bag_node_child_id`),
  CONSTRAINT `fk_bag_node_reference_bag_node1`
    FOREIGN KEY (`bag_node_parent_id`)
    REFERENCES `bag_of_tricks`.`bag_node` (`bag_node_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bag_node_reference_bag_node2`
    FOREIGN KEY (`bag_node_child_id`)
    REFERENCES `bag_of_tricks`.`bag_node` (`bag_node_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bag_of_tricks`.`user_bag_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bag_of_tricks`.`user_bag_node` (
  `bag_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_bag_role_cd` VARCHAR(10) NOT NULL,
  INDEX `fk_user_bag_bag_idx` (`bag_id` ASC),
  INDEX `fk_user_bag_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`bag_id`, `user_id`, `user_bag_role_cd`),
  CONSTRAINT `fk_user_bag_bag`
    FOREIGN KEY (`bag_id`)
    REFERENCES `bag_of_tricks`.`bag_node` (`bag_node_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_bag_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bag_of_tricks`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
