version: "2.0"

services:
  mysql:
    image: mysql:5.7.20
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: bag_of_tricks
      MYSQL_USER: bag_of_tricks
      MYSQL_DATABASE: bag_of_tricks
      MYSQL_ROOT_PASSWORD: root